CALIBRATION_HTML = r'''<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Potato Calibration</title>
  <script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/gsap.min.js"></script>
  <script src="https://unpkg.com/lucide@0.468.0/dist/umd/lucide.min.js"></script>
  <style>
    :root{--ink:#17201c;--muted:#69736d;--line:#dce2de;--paper:#f7f8f6;--white:#fff;--green:#176b4b;--mint:#dff3e8;--red:#a63e35;--amber:#a06112;--blue:#245f8c;--shadow:0 10px 30px rgba(23,32,28,.08)}
    *{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:14px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:0}button,input,textarea{font:inherit}button{cursor:pointer}
    header{height:64px;background:var(--ink);color:white;display:flex;align-items:center;padding:0 28px;gap:14px;position:sticky;top:0;z-index:10}.brand{font-size:17px;font-weight:700}.header-state{margin-left:auto;color:#b8c6bf;font-size:12px}
    .layout{display:grid;grid-template-columns:290px minmax(0,1fr);min-height:calc(100vh - 64px)}aside{border-right:1px solid var(--line);background:#eef1ee;padding:22px 16px}.agent-tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:4px;margin-bottom:12px}.agent-tabs button{border:0;background:transparent;padding:8px 4px;color:var(--muted);border-bottom:2px solid transparent}.agent-tabs button.active{color:var(--ink);border-color:var(--green);font-weight:700}.sidebar-actions{display:flex;align-items:center;gap:8px;margin-bottom:14px}.new-session{flex:1;border:1px solid var(--ink);background:var(--ink);color:#fff;border-radius:4px;padding:8px 10px;font-weight:650}.archive-toggle{display:flex;align-items:center;gap:5px;color:var(--muted);font-size:11px;white-space:nowrap}.archive-toggle input{width:auto}
    .session-list{display:grid;gap:6px}.session{width:100%;text-align:left;border:1px solid transparent;background:transparent;padding:11px 12px;border-radius:6px;color:var(--ink)}.session:hover{background:#fff}.session.active{background:#fff;border-color:#cbd6cf;box-shadow:0 3px 12px rgba(20,35,27,.06)}.session small{display:block;color:var(--muted);margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
    main{padding:28px 34px 60px;max-width:1180px;width:100%;margin:0 auto}.empty{padding:80px 20px;text-align:center;color:var(--muted)}.page-head{display:flex;align-items:flex-start;gap:20px;margin-bottom:24px}.page-head h1{font-size:25px;line-height:1.25;margin:0 0 7px}.page-head p{margin:0;color:var(--muted)}.page-actions{margin-left:auto;display:flex;align-items:center;gap:8px}.status{padding:5px 9px;border-radius:4px;background:var(--mint);color:var(--green);font-weight:700;font-size:12px}.status.closed{background:#e8ebe9;color:#68716c}.danger{border:1px solid #d6b5b0;background:white;color:var(--red);border-radius:4px;padding:7px 10px}.refresh{border:1px solid #bcc7c0;background:white;color:var(--ink);border-radius:4px;padding:7px 10px}
    .progress{display:grid;grid-template-columns:repeat(4,1fr);margin-bottom:24px;border:1px solid var(--line);background:white}.step{padding:14px 15px;border-right:1px solid var(--line)}.step:last-child{border:0}.step b{display:block;font-size:12px}.step span{color:var(--muted);font-size:11px}.step.done{box-shadow:inset 0 3px var(--green)}.step.current{box-shadow:inset 0 3px var(--amber);background:#fffaf1}
    .module{border-top:1px solid var(--line);background:white}.module:last-child{border-bottom:1px solid var(--line)}.module-head{width:100%;border:0;background:white;display:flex;align-items:center;gap:11px;padding:17px 16px;text-align:left}.module-head:hover{background:#fafbf9}.module-head strong{font-size:15px}.module-head .count{color:var(--muted);font-size:12px}.chevron{margin-left:auto;transition:transform .2s}.module.open .chevron{transform:rotate(180deg)}.module-body{display:none;padding:0 16px 20px;overflow:hidden}.module.open .module-body{display:block}
    .execution{border-left:3px solid #cbd6cf;padding:3px 0 3px 15px;margin:12px 0 24px}.execution h3{font-size:14px;margin:0 0 6px}.meta{display:flex;gap:12px;flex-wrap:wrap;color:var(--muted);font-size:12px}.reply{white-space:pre-wrap;background:#f5f7f5;padding:13px;margin-top:12px;border-radius:4px;max-height:260px;overflow:auto}.assets{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:14px;margin-top:14px}video{width:100%;max-height:500px;background:#111;border-radius:4px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.primary,.secondary,.icon-btn{border:1px solid var(--ink);border-radius:4px;padding:8px 12px;background:var(--ink);color:white;display:inline-flex;align-items:center;gap:7px}.secondary{background:white;color:var(--ink);border-color:#bcc7c0}.primary:disabled{opacity:.45;cursor:not-allowed}.run-form{border:1px solid var(--line);background:#fafbf9;padding:14px;margin:5px 0 20px}.run-form h3{font-size:13px;margin:0 0 9px}.run-form textarea{min-height:86px}
    .review-head{display:flex;align-items:center;gap:12px}.score{font-size:34px;font-weight:750;color:var(--green)}.verdict{font-weight:700}.hard{border-left:3px solid var(--red);padding:10px 12px;background:#fff7f6;margin:8px 0}.style{border-left:3px solid var(--blue);padding:10px 12px;background:#f5f9fc;margin:8px 0}.evidence-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:10px;margin-top:12px}.evidence-grid figure{margin:0}.evidence-grid img{width:100%;aspect-ratio:16/10;object-fit:cover;background:#e4e8e5;border-radius:4px}.evidence-grid figcaption{font-size:11px;color:var(--muted);margin-top:4px}
    .columns{display:grid;grid-template-columns:1fr 1fr;gap:22px}.columns h3{font-size:13px;margin:0 0 10px}.turn{padding:9px 0;border-bottom:1px solid #edf0ee}.turn b{display:block;font-size:11px;color:var(--muted)}textarea,input{width:100%;border:1px solid #bdc7c1;border-radius:4px;padding:10px;background:white;color:var(--ink)}textarea{min-height:100px;resize:vertical}.candidate-form{display:grid;gap:10px}.candidate-form textarea.prompt{min-height:220px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px}
    .login{max-width:390px;margin:100px auto;background:white;border:1px solid var(--line);padding:28px;box-shadow:var(--shadow)}.login h1{font-size:21px;margin:0 0 8px}.login p{color:var(--muted)}.login .primary{margin-top:12px;width:100%;justify-content:center}.error{color:var(--red);margin-top:8px}.hidden{display:none!important}dialog{width:min(520px,calc(100vw - 32px));border:1px solid var(--line);border-radius:7px;padding:0;box-shadow:0 24px 70px rgba(20,29,25,.24);color:var(--ink)}dialog::backdrop{background:rgba(18,25,22,.46)}.dialog-head{padding:20px 22px 13px;border-bottom:1px solid var(--line);display:flex;align-items:center}.dialog-head h2{font-size:18px;margin:0}.dialog-close{margin-left:auto;border:0;background:transparent;font-size:21px;color:var(--muted)}.dialog-body{padding:18px 22px;display:grid;gap:14px}.field label{display:block;font-size:12px;font-weight:700;margin-bottom:6px}.segments{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.segments label{border:1px solid var(--line);padding:8px;text-align:center;border-radius:4px;cursor:pointer}.segments input{position:absolute;opacity:0;width:1px}.segments label:has(input:checked){border-color:var(--green);background:var(--mint);color:var(--green);font-weight:700}.transport{grid-template-columns:1fr 1fr}.dialog-actions{padding:0 22px 20px;display:flex;justify-content:flex-end;gap:8px}.dialog-note{color:var(--muted);font-size:12px;margin:0}
    @media(max-width:760px){header{padding:0 16px}.layout{grid-template-columns:1fr}aside{border-right:0;border-bottom:1px solid var(--line);padding:12px}.session-list{display:flex;overflow:auto}.session{min-width:210px}main{padding:22px 16px}.progress{grid-template-columns:1fr 1fr}.step:nth-child(2){border-right:0}.columns{grid-template-columns:1fr}.page-head{display:block}.page-actions{margin:12px 0 0}.segments{grid-template-columns:1fr}.transport{grid-template-columns:1fr 1fr}}
  </style>
</head>
<body>
<div id="login" class="login hidden"><h1>校准控制台</h1><p>输入 Potato Gateway Bearer Token。</p><input id="token" type="password" autocomplete="current-password"><button class="primary" onclick="login()"><i data-lucide="log-in" width="16"></i>进入</button><div id="loginError" class="error"></div></div>
<div id="app" class="hidden"><header><i data-lucide="scan-eye" width="20"></i><span class="brand">Potato Calibration</span><span class="header-state" id="syncState">已连接</span></header><div class="layout"><aside><div class="agent-tabs" id="agentTabs"></div><div class="sidebar-actions"><button class="new-session" onclick="openCreateDialog()">+ 新建校准</button><label class="archive-toggle"><input id="showArchived" type="checkbox" onchange="toggleArchived(this.checked)">已归档</label></div><div class="session-list" id="sessions"></div></aside><main id="detail"><div class="empty">选择一个校准 Session</div></main></div></div>
<dialog id="createDialog"><div class="dialog-head"><h2>新建校准 Session</h2><button class="dialog-close" onclick="closeDialog('createDialog')" aria-label="关闭">×</button></div><div class="dialog-body"><div class="field"><label>Agent</label><div class="segments" id="createAgents"></div></div><div class="field"><label>执行方式</label><div class="segments transport"><label><input type="radio" name="transport" value="hub" checked>Hub 自动执行</label><label><input type="radio" name="transport" value="manual">手动记录</label></div></div><div class="field"><label for="sessionGoal">校准目标</label><input id="sessionGoal" maxlength="4000" placeholder="例如：建立 9:16 动态视频 baseline"></div><div class="field"><label for="sessionCriteria">验收标准</label><textarea id="sessionCriteria" placeholder="每行一条标准"></textarea></div><p class="dialog-note">Session 会锁定当前 Prompt 指纹，后续候选版本不会自动发布。</p><div id="createError" class="error"></div></div><div class="dialog-actions"><button class="secondary" onclick="closeDialog('createDialog')">取消</button><button class="primary" onclick="createSession()">创建 Session</button></div></dialog>
<dialog id="archiveDialog"><div class="dialog-head"><h2>归档校准 Session</h2><button class="dialog-close" onclick="closeDialog('archiveDialog')" aria-label="关闭">×</button></div><div class="dialog-body"><p>归档后默认从列表隐藏，校准记录与证据仍会保留。</p><div id="archiveError" class="error"></div></div><div class="dialog-actions"><button class="secondary" onclick="closeDialog('archiveDialog')">取消</button><button class="danger" onclick="archiveSession()">确认归档</button></div></dialog>
<script>
const agents={creator:'清蒸土豆',researcher:'薯博士',critic:'酸辣土豆丝'};let agent='creator',selected='',token='',state={},showArchived=false,pollTimer=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Authorization':`Bearer ${token}`,'Content-Type':'application/json',...(options.headers||{})}});if(r.status===401)throw new Error('unauthorized');const body=await r.json();if(!r.ok)throw new Error(body.detail||body.error||`HTTP ${r.status}`);return body}
function boot(){token=localStorage.getItem('potatoGatewayToken')||'';if(!token){showLogin();return}document.querySelector('#app').classList.remove('hidden');renderTabs();loadSessions()}
function showLogin(msg=''){document.querySelector('#app').classList.add('hidden');document.querySelector('#login').classList.remove('hidden');document.querySelector('#loginError').textContent=msg}
async function login(){token=document.querySelector('#token').value.trim();try{await api('/api/status');localStorage.setItem('potatoGatewayToken',token);document.querySelector('#login').classList.add('hidden');document.querySelector('#app').classList.remove('hidden');renderTabs();loadSessions()}catch(e){showLogin('Token 无效或 Gateway 不可用')}}
function renderTabs(){document.querySelector('#agentTabs').innerHTML=Object.entries(agents).map(([id,name])=>`<button class="${id===agent?'active':''}" onclick="setAgent('${id}')">${name.replace('土豆','')}</button>`).join('');document.querySelector('#createAgents').innerHTML=Object.entries(agents).map(([id,name])=>`<label><input type="radio" name="createAgent" value="${id}" ${id===agent?'checked':''}>${name}</label>`).join('');window.lucide?.createIcons()}
function setAgent(id){agent=id;selected='';clearTimeout(pollTimer);renderTabs();loadSessions()}
function toggleArchived(value){showArchived=value;selected='';loadSessions()}
function openCreateDialog(){document.querySelector('#createError').textContent='';document.querySelector('#sessionGoal').value='';document.querySelector('#sessionCriteria').value='';const choice=document.querySelector(`input[name="createAgent"][value="${agent}"]`);if(choice)choice.checked=true;document.querySelector('#createDialog').showModal()}
function closeDialog(id){document.querySelector(`#${id}`).close()}
async function createSession(){const button=document.querySelector('#createDialog .primary'),error=document.querySelector('#createError'),chosen=document.querySelector('input[name="createAgent"]:checked'),transport=document.querySelector('input[name="transport"]:checked')?.value||'hub',goal=document.querySelector('#sessionGoal').value.trim(),criteria=document.querySelector('#sessionCriteria').value.split('\n').map(x=>x.trim()).filter(Boolean);error.textContent='';if(!chosen||!goal){error.textContent='请选择 Agent，并填写校准目标。';return}button.disabled=true;button.textContent='创建中…';try{const created=await api('/api/calibrations',{method:'POST',body:JSON.stringify({client_request_id:`ui-session-${crypto.randomUUID()}`,agent_id:chosen.value,transport,goal,acceptance_criteria:criteria})});agent=chosen.value;selected=created.session_id;closeDialog('createDialog');renderTabs();await loadSessions();await refreshDetail()}catch(e){error.textContent=e.message}finally{button.disabled=false;button.textContent='创建 Session'}}
function openArchiveDialog(){document.querySelector('#archiveError').textContent='';document.querySelector('#archiveDialog').showModal()}
async function archiveSession(){const button=document.querySelector('#archiveDialog .danger'),error=document.querySelector('#archiveError');button.disabled=true;button.textContent='归档中…';error.textContent='';try{await api(`/api/calibrations/${selected}`,{method:'DELETE'});closeDialog('archiveDialog');selected='';await loadSessions()}catch(e){error.textContent=e.message}finally{button.disabled=false;button.textContent='确认归档'}}
async function restoreSession(){try{await api(`/api/calibrations/${selected}/restore`,{method:'POST',body:'{}'});await loadSessions();await refreshDetail()}catch(e){alert(e.message)}}
async function loadSessions(){try{const data=await api(`/api/agents/${agent}/calibrations?limit=100`),visible=data.sessions.filter(s=>showArchived||s.state!=='closed');document.querySelector('#sessions').innerHTML=visible.map(s=>`<button class="session ${s.session_id===selected?'active':''}" onclick="selectSession('${esc(s.session_id)}')"><strong>${esc(s.goal)}</strong><small>${new Date(s.updated_at).toLocaleString()} · ${s.state==='closed'?'已归档':esc(s.state)}</small></button>`).join('')||'<div class="empty">暂无 Session</div>';if(!selected&&visible[0])selectSession(visible[0].session_id);if(!visible.length)document.querySelector('#detail').innerHTML='<div class="empty">点击“新建校准”开始</div>'}catch(e){if(e.message==='unauthorized')showLogin('登录已失效');else document.querySelector('#sessions').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
async function selectSession(id){selected=id;loadSessions();await refreshDetail()}
async function refreshDetail(){if(!selected)return;clearTimeout(pollTimer);document.querySelector('#syncState').textContent='同步中';try{const [session,execs,reviews,prompts]=await Promise.all([api(`/api/calibrations/${selected}`),api(`/api/calibrations/${selected}/executions`),api(`/api/calibrations/${selected}/reviews`),api(`/api/agents/${agent}/prompt-versions?limit=20`)]);state={session,execs:execs.executions,reviews:reviews.reviews,prompts:prompts.versions};await renderDetail();document.querySelector('#syncState').textContent='刚刚同步';if(state.execs.some(x=>['queued','running'].includes(x.status))||state.reviews.some(x=>['queued','preparing','reviewing'].includes(x.status)))pollTimer=setTimeout(refreshDetail,5000)}catch(e){document.querySelector('#detail').innerHTML=`<div class="error">${esc(e.message)}</div>`;document.querySelector('#syncState').textContent='同步失败'}}
function stage(){const ex=state.execs||[],rv=state.reviews||[];if(rv.some(x=>x.status==='completed'))return 4;if(rv.some(x=>['queued','preparing','reviewing'].includes(x.status)))return 3;if(ex.some(x=>x.status==='completed'))return 2;return 1}
async function renderDetail(){const s=state.session,step=stage(),links={};for(const ex of state.execs){for(const id of ex.asset_ids){try{links[id]=await api(`/api/calibrations/${selected}/assets/${id}/link`)}catch{}}}state.links=links;document.querySelector('#detail').innerHTML=`
<div class="page-head"><div><h1>${esc(s.goal)}</h1><p>${agents[s.agent_id]} · ${esc(s.session_id)} · ${esc(s.transport)}</p></div><div class="page-actions"><button class="refresh" onclick="refreshDetail()">刷新</button>${s.state==='closed'?`<button class="secondary" onclick="restoreSession()">恢复</button>`:`<button class="danger" onclick="openArchiveDialog()">归档</button>`}<span class="status ${s.state==='closed'?'closed':''}">${s.state==='closed'?'已归档':esc(s.state)}</span></div></div>
<div class="progress">${['测试要求','真实生成','独立评审','人工决策'].map((x,i)=>`<div class="step ${i+1<step?'done':i+1===step?'current':''}"><b>${x}</b><span>${i+1<step?'已完成':i+1===step?'当前阶段':'待处理'}</span></div>`).join('')}</div>
${module('execution','真实回复与素材',state.execs.length,renderExecutions(),true)}
${module('review','酸辣土豆丝评审',state.reviews.length,renderReviews(),true)}
${module('evidence','逐镜头证据','按需加载','<div id="evidenceArea"><p class="meta">展开某份已完成评审后加载关键帧。</p></div>')}
${module('feedback','你的反馈与系统记录',s.turns.length,renderFeedback())}
${module('prompt','Prompt Candidate',state.prompts.length,renderCandidates())}`;bindModules();window.lucide?.createIcons();animateIn();for(const r of state.reviews.filter(x=>x.status==='completed'))loadEvidence(r.review_id)}
function module(id,title,count,body,open=false){return `<section class="module ${open?'open':''}" data-module="${id}"><button class="module-head"><i data-lucide="${({execution:'film',review:'badge-check',evidence:'images',feedback:'messages-square',prompt:'file-pen-line'})[id]}" width="18"></i><strong>${title}</strong><span class="count">${count}</span><i class="chevron" data-lucide="chevron-down" width="17"></i></button><div class="module-body">${body}</div></section>`}
function renderExecutions(){const form=state.session.transport==='hub'&&state.session.state==='calibrating'?`<div class="run-form"><h3>提交校准测试</h3><textarea id="testInstruction" placeholder="输入这次要 Agent 真实完成的测试要求"></textarea><div class="actions"><button class="primary" onclick="executeTest()">运行测试</button></div></div>`:'';if(!state.execs.length)return `${form}<p class="meta">还没有校准执行。</p>`;return form+state.execs.map(ex=>{const videoId=ex.asset_ids.find(id=>state.links[id]?.asset_type==='video');return `<article class="execution"><h3>${esc(ex.instruction)}</h3><div class="meta"><span>${esc(ex.status)}</span><span>${new Date(ex.created_at).toLocaleString()}</span><span>${ex.asset_ids.length} 个素材</span></div>${ex.response?`<div class="reply">${esc(ex.response)}</div>`:''}<div class="assets">${ex.asset_ids.map(id=>state.links[id]?.asset_type==='video'?`<video controls preload="metadata" src="${esc(state.links[id].url)}"></video>`:`<div class="meta">${esc(state.links[id]?.title||`Asset #${id}`)}</div>`).join('')}</div>${agent==='creator'&&ex.status==='completed'&&videoId?`<div class="actions"><button class="primary" onclick="createReview('${ex.execution_id}',${videoId})"><i data-lucide="scan-eye" width="16"></i>交给酸辣土豆丝评审</button></div>`:''}</article>`}).join('')}
function renderReviews(){if(!state.reviews.length)return '<p class="meta">完成 creator 视频后，由你手动发起评审。</p>';return state.reviews.map(r=>{const p=r.report||{};return `<article class="execution"><div class="review-head"><div><h3>${esc(p.summary||'评审处理中')}</h3><div class="meta">${esc(r.status)} · ${esc(r.review_id)}</div></div>${p.total_score!==undefined?`<div class="score">${esc(p.total_score)}</div>`:''}</div>${p.verdict?`<p class="verdict">建议：${esc(p.verdict)}</p>`:''}${(p.hard_errors||[]).map(x=>`<div class="hard"><strong>硬错误</strong><br>${esc(x.problem||x.description||'')}<div class="meta">${esc(x.time_range||'')}</div></div>`).join('')}${(p.style_findings||[]).map(x=>`<div class="style"><strong>${esc(x.category||'风格观察')}</strong><br>${esc(x.observation||x.description||'')}<div class="meta">${esc(x.time_range||'')}</div></div>`).join('')}${r.status==='failed'?`<div class="error">${esc(r.error)}</div>`:''}</article>`}).join('')}
function renderFeedback(){const user=state.session.turns.filter(t=>['user','commander'].includes(t.actor)),critic=state.session.turns.filter(t=>t.actor==='evaluator');return `<div class="columns"><div><h3>你的判断</h3>${user.map(turn).join('')||'<p class="meta">暂无反馈</p>'}<textarea id="feedbackText" placeholder="记录整体方向、动态感、节奏或事实问题"></textarea><button class="secondary" onclick="saveFeedback()"><i data-lucide="save" width="16"></i>保存反馈</button></div><div><h3>独立评审记录</h3>${critic.map(turn).join('')||'<p class="meta">尚未完成 critic 评审</p>'}</div></div>`}
const turn=t=>`<div class="turn"><b>${esc(t.actor)} · ${new Date(t.created_at).toLocaleString()}</b>${esc(t.content)}</div>`;
function renderCandidates(){return `<div class="columns"><div>${state.prompts.map(p=>`<div class="turn"><b>${esc(p.status)} · ${p.content_sha256.slice(0,12)}</b>${esc(p.change_summary)}</div>`).join('')||'<p class="meta">暂无候选版本</p>'}</div><div class="candidate-form"><input id="candidateSummary" placeholder="这次候选版本改了什么"><textarea id="candidateContent" class="prompt" placeholder="候选 Prompt 正文"></textarea><button class="primary" onclick="createCandidate()"><i data-lucide="file-plus-2" width="16"></i>创建 Draft Candidate</button><p class="meta">创建不会发布。存在未解决硬错误时，后台会拒绝激活。</p></div></div>`}
function bindModules(){document.querySelectorAll('.module-head').forEach(btn=>btn.onclick=()=>{const mod=btn.closest('.module'),body=mod.querySelector('.module-body'),opening=!mod.classList.contains('open');if(!window.gsap||matchMedia('(prefers-reduced-motion: reduce)').matches){mod.classList.toggle('open',opening);return}if(opening){mod.classList.add('open');gsap.fromTo(body,{height:0,autoAlpha:0},{height:'auto',autoAlpha:1,duration:.28,ease:'power1.out',clearProps:'height,opacity,visibility'})}else{gsap.to(body,{height:0,autoAlpha:0,duration:.2,ease:'power1.in',onComplete:()=>{mod.classList.remove('open');gsap.set(body,{clearProps:'height,opacity,visibility'})}})}})}
function animateIn(){if(window.gsap&&!matchMedia('(prefers-reduced-motion: reduce)').matches)gsap.from('.module',{y:10,autoAlpha:0,duration:.32,stagger:.04,ease:'power1.out'})}
async function executeTest(){const input=document.querySelector('#testInstruction'),button=input?.parentElement.querySelector('.primary'),instruction=input?.value.trim();if(!instruction)return;if(button){button.disabled=true;button.textContent='提交中…'}try{await api(`/api/calibrations/${selected}/executions`,{method:'POST',body:JSON.stringify({client_turn_id:`ui-test-${crypto.randomUUID()}`,instruction})});await refreshDetail()}catch(e){alert(e.message)}finally{if(button){button.disabled=false;button.textContent='运行测试'}}}
async function createReview(executionId,assetId){try{await api(`/api/calibrations/${selected}/executions/${executionId}/reviews`,{method:'POST',body:JSON.stringify({client_request_id:`ui-${executionId}-${assetId}`,source_asset_id:assetId})});await refreshDetail()}catch(e){alert(e.message)}}
async function loadEvidence(reviewId){try{const e=await api(`/api/calibrations/${selected}/reviews/${reviewId}/evidence`);const area=document.querySelector('#evidenceArea');if(!area)return;area.innerHTML=`<div class="meta">${e.frames.length} 帧 · 转写 ${esc(e.transcript_status)}</div><div class="evidence-grid">${e.contact_sheets.map((x,i)=>`<figure><img src="${esc(x.url)}" alt="Contact sheet ${i+1}"><figcaption>Contact sheet ${i+1} · Asset #${x.asset_id}</figcaption></figure>`).join('')}${e.frames.map(x=>`<figure><img loading="lazy" src="${esc(x.url)}" alt="镜头 ${x.shot_index}"><figcaption>${esc(x.description)} · ${x.timestamp_seconds}s</figcaption></figure>`).join('')}</div>`}catch(e){const area=document.querySelector('#evidenceArea');if(area)area.innerHTML=`<div class="error">${esc(e.message)}</div>`}}
async function saveFeedback(){const content=document.querySelector('#feedbackText').value.trim();if(!content)return;await api(`/api/calibrations/${selected}/turns`,{method:'POST',body:JSON.stringify({client_turn_id:`ui-feedback-${Date.now()}`,actor:'user',kind:'critique',content})});await refreshDetail()}
async function createCandidate(){const content=document.querySelector('#candidateContent').value.trim(),summary=document.querySelector('#candidateSummary').value.trim();if(!content||!summary)return;await api(`/api/agents/${agent}/prompt-versions`,{method:'POST',body:JSON.stringify({client_request_id:`ui-candidate-${Date.now()}`,content,change_summary:summary,calibration_session_id:selected})});await refreshDetail()}
boot();
</script></body></html>'''
