HOME_HTML = r'''<!doctype html>
<html lang="zh-CN" class="no-gsap">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Potato 工作台</title>
  <script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/gsap.min.js"></script>
  <script src="https://unpkg.com/lucide@0.468.0/dist/umd/lucide.min.js"></script>
  <style>
    :root{--ink:#18211d;--muted:#6d7771;--line:#dbe2dd;--paper:#f4f6f4;--white:#fff;--green:#176b4b;--green-soft:#e2f1e9;--coral:#b85542;--coral-soft:#f7e8e3;--blue:#285f87;--blue-soft:#e7eff5;--shadow:0 14px 34px rgba(24,33,29,.08)}
    *{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--paper);color:var(--ink);font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:0}a{color:inherit;text-decoration:none}button{font:inherit}
    header{height:62px;background:var(--ink);color:white;display:flex;align-items:center;padding:0 max(22px,calc((100vw - 1040px)/2));gap:11px}.mark{width:28px;height:28px;border:1px solid #53605a;display:grid;place-items:center;border-radius:5px;font-weight:800;font-size:12px}.brand{font-size:16px;font-weight:720}.gateway-state{margin-left:auto;color:#c3cec8;font-size:12px;display:flex;align-items:center;gap:7px}.dot{width:7px;height:7px;border-radius:50%;background:#68c69c;box-shadow:0 0 0 3px rgba(104,198,156,.13)}
    main{max-width:1040px;margin:0 auto;padding:54px 24px 72px}.heading{display:flex;align-items:end;justify-content:space-between;margin-bottom:20px}.heading h1{font-size:26px;line-height:1.2;margin:0;font-weight:750}.heading time{color:var(--muted);font-size:12px}
    .launchers{display:grid;grid-template-columns:1fr 1fr;gap:16px}.launcher{min-height:238px;background:var(--white);border:1px solid var(--line);border-radius:7px;padding:24px;display:flex;flex-direction:column;position:relative;overflow:hidden;box-shadow:0 2px 0 rgba(24,33,29,.02);transition:border-color .18s,box-shadow .18s,transform .18s}.launcher:hover{transform:translateY(-2px);box-shadow:var(--shadow)}.launcher.workflow:hover{border-color:#dab6ac}.launcher.calibration:hover{border-color:#a9d0bc}.launcher:focus-visible{outline:3px solid rgba(40,95,135,.22);outline-offset:3px}.topline{display:flex;align-items:center;justify-content:space-between}.app-icon{width:45px;height:45px;border-radius:6px;display:grid;place-items:center;font-weight:800;font-size:13px}.workflow .app-icon{background:var(--coral-soft);color:var(--coral)}.calibration .app-icon{background:var(--green-soft);color:var(--green)}.arrow{width:34px;height:34px;border:1px solid var(--line);border-radius:50%;display:grid;place-items:center;font-size:18px}.launcher h2{font-size:21px;margin:38px 0 5px}.meta{color:var(--muted);font-size:12px}.status-line{margin-top:auto;display:flex;align-items:center;gap:7px;font-size:12px;font-weight:650}.status-line::before{content:"";width:6px;height:6px;border-radius:50%;background:#a9b3ad}.status-line.online::before{background:#4bae7d}.status-line.offline{color:#9b4339}.status-line.offline::before{background:#c45c4e}
    .tools{margin-top:32px;border-top:1px solid var(--line)}.tools-head{display:flex;align-items:center;padding:17px 2px 11px}.tools-head h2{font-size:13px;margin:0}.tools-list{display:grid;grid-template-columns:repeat(3,1fr);background:var(--white);border:1px solid var(--line);border-radius:6px}.tool{padding:15px 17px;border-right:1px solid var(--line);display:flex;align-items:center;gap:11px;min-width:0}.tool:last-child{border:0}.tool:hover{background:#fafbfa}.tool-icon{width:30px;height:30px;border-radius:5px;background:var(--blue-soft);color:var(--blue);display:grid;place-items:center;font-size:10px;font-weight:800;flex:0 0 auto}.tool strong{display:block;font-size:13px}.tool span{display:block;color:var(--muted);font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tool .go{margin-left:auto;color:#8a948e}
    #agents{margin-top:34px}.agents-heading{display:flex;align-items:end;justify-content:space-between;padding:0 2px 11px}.agents-heading h2{font-size:13px;margin:0}.agents-heading span{font-size:11px;color:var(--muted)}.agent-row{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.agent{--agent-accent:var(--blue);--agent-soft:var(--blue-soft);min-width:0;background:var(--white);border:1px solid var(--line);border-top:3px solid var(--agent-accent);border-radius:6px;padding:14px;display:grid;grid-template-columns:76px minmax(0,1fr);gap:11px;align-items:center;box-shadow:0 2px 0 rgba(24,33,29,.02)}.agent[data-agent="creator"]{--agent-accent:var(--coral);--agent-soft:var(--coral-soft)}.agent[data-agent="critic"]{--agent-accent:#bc3e38;--agent-soft:#fae8df}.agent[data-agent="engineer"]{--agent-accent:#405f75;--agent-soft:#e5f1f2}.agent-copy{min-width:0}.agent-title{display:flex;align-items:center;gap:6px}.agent-title b{font-size:13px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.agent-title i{color:var(--agent-accent);flex:0 0 auto}.agent-role{display:block;color:var(--muted);font-size:10px;margin-top:1px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.agent-activity{display:block;font-size:11px;font-weight:700;margin-top:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.agent-state{display:inline-flex;align-items:center;gap:5px;margin-top:5px;color:var(--muted);font-size:10px}.agent-state::before{content:"";width:6px;height:6px;border-radius:50%;background:#9ea8a2}.agent[data-state="idle"] .agent-state{color:var(--green)}.agent[data-state="idle"] .agent-state::before{background:#4bae7d}.agent[data-state="working"] .agent-state,.agent[data-state="calibrating"] .agent-state{color:var(--agent-accent)}.agent[data-state="working"] .agent-state::before,.agent[data-state="calibrating"] .agent-state::before{background:var(--agent-accent)}.agent[data-state="error"] .agent-state,.agent[data-state="offline"] .agent-state{color:#9b4339}.agent[data-state="error"] .agent-state::before,.agent[data-state="offline"] .agent-state::before{background:#c45c4e}
    .potato-scene{width:76px;height:78px;position:relative;display:grid;place-items:center}.potato-body{width:50px;height:56px;position:relative;border:1px solid #9d7439;border-radius:45% 55% 48% 52% / 52% 44% 56% 48%;background:#d6a657;box-shadow:inset -7px -8px 0 rgba(116,72,24,.11),0 4px 0 rgba(77,54,25,.08);transform-origin:50% 86%;will-change:transform;z-index:1}.potato-body::before{content:"";position:absolute;width:3px;height:3px;border-radius:50%;background:#aa7738;left:9px;top:13px;box-shadow:29px 8px #b17b3c,7px 31px #b17b3c,30px 35px #b17b3c}.eye{position:absolute;z-index:4;top:22px;width:4px;height:6px;border-radius:50%;background:#352b20;transform-origin:center}.eye.left{left:15px}.eye.right{right:15px}.mouth{position:absolute;z-index:4;left:50%;top:36px;width:11px;height:6px;transform:translateX(-50%);border-bottom:2px solid #5f4022;border-radius:0 0 50% 50%}.cheek{position:absolute;z-index:3;top:31px;width:6px;height:3px;border-radius:50%;background:rgba(190,83,64,.28)}.cheek.left{left:8px}.cheek.right{right:8px}.state-glyph{position:absolute;z-index:8;right:0;top:1px;min-width:22px;height:22px;border:1px solid color-mix(in srgb,var(--agent-accent) 42%,white);background:var(--agent-soft);color:var(--agent-accent);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:10px;font-weight:900}.work-dots{display:flex;gap:2px}.work-dots i{display:block;width:3px;height:3px;border-radius:50%;background:currentColor}
    .scholar-cap{position:absolute;z-index:7;left:3px;top:-9px;width:45px;height:10px;background:#294963;clip-path:polygon(50% 0,100% 50%,50% 100%,0 50%)}.scholar-cap::before{content:"";position:absolute;left:13px;top:7px;width:24px;height:8px;border-radius:0 0 7px 7px;background:#365f7d}.cap-tassel{position:absolute;z-index:8;right:2px;top:-3px;width:1px;height:18px;background:#d8ad44;transform-origin:top}.cap-tassel::after{content:"";position:absolute;left:-2px;bottom:-2px;width:5px;height:5px;border-radius:50%;background:#d8ad44}.glasses{position:absolute;z-index:6;left:7px;top:17px;width:36px;height:15px}.glasses::before,.glasses::after{content:"";position:absolute;top:0;width:13px;height:13px;border:2px solid #243c4f;border-radius:50%;background:rgba(226,242,248,.24)}.glasses::before{left:0}.glasses::after{right:0}.glasses-bridge{position:absolute;left:15px;top:6px;width:6px;height:2px;background:#243c4f}.bowtie{position:absolute;z-index:5;left:18px;bottom:3px;width:14px;height:8px;background:#bf5545;clip-path:polygon(0 0,50% 38%,100% 0,100% 100%,50% 62%,0 100%)}
    .agent[data-agent="creator"] .potato-body{background:#f5e8c8;border-color:#c9b786;border-radius:49% 51% 48% 52% / 45% 47% 53% 55%;box-shadow:inset -7px -8px 0 rgba(165,137,79,.1),0 4px 0 rgba(77,54,25,.06)}.agent[data-agent="creator"] .potato-body::before{background:#e2cf9f;box-shadow:28px 14px #ead9b1,8px 34px #e2cf9f;opacity:.55}.steam-puff{position:absolute;z-index:6;top:-11px;width:7px;height:16px;border-left:2px solid #a9c9c7;border-radius:50%;opacity:.65}.steam-puff.one{left:12px}.steam-puff.two{left:25px;top:-14px}.steam-puff.three{left:37px}.clapper{position:absolute;z-index:7;right:-11px;bottom:1px;width:25px;height:18px;border:1px solid #303d42;border-radius:2px;background:#f5f7f5;box-shadow:0 2px 0 rgba(24,33,29,.12);transform:rotate(-7deg)}.clapper::before{content:"";position:absolute;left:-1px;top:-6px;width:25px;height:7px;border:1px solid #303d42;background:repeating-linear-gradient(135deg,#303d42 0 5px,#f5f7f5 5px 9px);transform-origin:left bottom}.clapper::after{content:"REC";position:absolute;left:4px;top:4px;color:#b85542;font-size:5px;font-weight:900}.play-dot{position:absolute;z-index:8;right:-6px;bottom:5px;width:5px;height:5px;border-radius:50%;background:#d45145}
    .agent[data-agent="critic"] .potato-body{width:56px;height:43px;margin-top:13px;border-color:#c88d43;border-radius:28% 28% 48% 48% / 22% 22% 68% 68%;background:#f2c15a;box-shadow:inset 0 -9px 0 rgba(191,94,42,.11),0 4px 0 rgba(77,54,25,.07)}.agent[data-agent="critic"] .potato-body::before{display:none}.agent[data-agent="critic"] .eye{top:19px}.agent[data-agent="critic"] .eye.left{left:17px}.agent[data-agent="critic"] .eye.right{right:17px}.agent[data-agent="critic"] .mouth{top:30px}.agent[data-agent="critic"] .cheek{top:27px}.shreds{position:absolute;z-index:2;left:4px;top:-15px;width:48px;height:22px}.shreds i{position:absolute;bottom:0;width:5px;height:22px;border-radius:5px 5px 2px 2px;background:#f7d77e;border:1px solid #d9a94d;transform-origin:bottom}.shreds i:nth-child(1){left:4px;transform:rotate(-17deg);height:18px}.shreds i:nth-child(2){left:13px;transform:rotate(8deg)}.shreds i:nth-child(3){left:22px;transform:rotate(-4deg);height:19px}.shreds i:nth-child(4){left:31px;transform:rotate(15deg);height:21px}.shreds i:nth-child(5){left:39px;transform:rotate(25deg);height:16px}.chili-mark{position:absolute;z-index:6;left:-5px;top:0;width:27px;height:7px;border-radius:70% 25% 60% 30%;background:#d53d35;transform:rotate(18deg);box-shadow:inset -5px -2px 0 rgba(122,29,23,.15)}.chili-mark::after{content:"";position:absolute;left:-4px;top:-2px;width:6px;height:4px;border-top:2px solid #3f8b4d;transform:rotate(-28deg)}.lime-slice{position:absolute;z-index:6;right:-7px;top:1px;width:18px;height:18px;border:3px solid #5b9f58;border-radius:50%;background:conic-gradient(#dce98c 0 24%,#fff 24% 27%,#dce98c 27% 49%,#fff 49% 52%,#dce98c 52% 74%,#fff 74% 77%,#dce98c 77%)}
    .agent[data-agent="engineer"] .potato-body{background:#d8a14f;border-color:#77552c;border-radius:40% 60% 45% 55% / 47% 41% 59% 53%;box-shadow:inset -8px -8px 0 rgba(54,76,86,.13),0 4px 0 rgba(29,47,58,.1)}.agent[data-agent="engineer"] .potato-body::before{background:#486a79;box-shadow:31px 23px #486a79,6px 35px #8b6422;width:3px;height:3px}.digital-visor{position:absolute;z-index:6;left:5px;top:17px;width:40px;height:17px;border:2px solid #284a59;border-radius:5px 7px 5px 7px;background:linear-gradient(90deg,rgba(70,198,197,.85),rgba(121,229,199,.72));box-shadow:0 0 0 2px rgba(225,255,248,.33) inset}.digital-visor::before,.digital-visor::after{content:"";position:absolute;top:5px;width:4px;height:4px;background:#173942;box-shadow:0 0 5px #dcfff5}.digital-visor::before{left:8px}.digital-visor::after{right:8px}.agent[data-agent="engineer"] .eye{opacity:0}.circuit-antenna{position:absolute;z-index:5;left:22px;top:-12px;width:18px;height:16px;border-left:2px solid #385969;border-top:2px solid #385969}.circuit-antenna::before,.circuit-antenna::after{content:"";position:absolute;width:6px;height:6px;background:#54c5b4;border:1px solid #254957}.circuit-antenna::before{right:-3px;top:-4px}.circuit-antenna::after{left:-4px;bottom:-3px}.code-badge{position:absolute;z-index:7;left:10px;bottom:3px;min-width:30px;padding:1px 3px;border:1px solid #2e4c5b;border-radius:3px;background:#233943;color:#9cf0ce;font:700 7px/10px ui-monospace,SFMono-Regular,Menlo,monospace;text-align:center}.pixel-tail{position:absolute;z-index:0;right:-8px;bottom:7px;width:13px;height:18px;border-right:5px solid #405f75;border-bottom:5px solid #405f75;transform:skewY(-18deg)}
    @media(prefers-reduced-motion:no-preference){.cap-tassel{animation:tassel-sway 2.6s ease-in-out infinite}.steam-puff{animation:steam-rise 2.2s ease-in-out infinite}.steam-puff.two{animation-delay:.45s}.steam-puff.three{animation-delay:.9s}.chili-mark{animation:chili-wiggle 2.4s ease-in-out infinite}.digital-visor{animation:visor-glow 2s ease-in-out infinite}}
    @keyframes tassel-sway{50%{transform:rotate(9deg)}}@keyframes steam-rise{0%,100%{transform:translateY(3px);opacity:.15}50%{transform:translateY(-3px);opacity:.72}}@keyframes chili-wiggle{50%{transform:rotate(12deg) translateY(-1px)}}@keyframes visor-glow{50%{filter:brightness(1.2);box-shadow:0 0 8px rgba(84,197,180,.38)}}
    .agent[data-state="working"] .mouth{height:4px;border:0;border-top:2px solid #5f4022;border-radius:50% 50% 0 0}.agent[data-state="calibrating"] .eye{height:7px;background:transparent;border:1px solid #352b20}.agent[data-agent="engineer"][data-state="calibrating"] .eye{opacity:0}.agent[data-state="error"] .mouth{top:39px;border:0;border-top:2px solid #7a332b;border-radius:50% 50% 0 0}.agent[data-agent="critic"][data-state="error"] .mouth{top:33px}.agent[data-state="error"] .potato-body{filter:saturate(.68)}.agent[data-state="offline"] .potato-body,.agent[data-state="unknown"] .potato-body{filter:grayscale(.72);opacity:.7}.agent[data-state="offline"] .eye{height:1px;border-radius:0}.agent[data-state="offline"] .mouth{width:7px;height:3px}.agent-empty{grid-column:1/-1;padding:20px;background:#fff;border:1px solid var(--line);color:var(--muted);text-align:center}
    @keyframes potato-breathe{50%{transform:scale(1.02,.97)}}@keyframes potato-blink{0%,92%,100%{transform:scaleY(1)}94%,98%{transform:scaleY(.08)}}@keyframes potato-work{50%{transform:translateY(-3px) rotate(2deg)}}@keyframes potato-dot{50%{transform:translateY(-3px)}}@keyframes potato-spin{to{transform:rotate(360deg)}}@keyframes potato-pulse{50%{transform:scale(1.035)}}@keyframes potato-alert{25%{transform:rotate(2deg)}75%{transform:rotate(-2deg)}}@keyframes potato-sleep{50%{transform:translateY(-4px);opacity:.42}}
    .no-gsap .agent[data-state="idle"] .potato-body{animation:potato-breathe 3.6s ease-in-out infinite}.no-gsap .agent[data-state="idle"] .eye{animation:potato-blink 3s linear infinite}.no-gsap .agent[data-state="working"] .potato-body{animation:potato-work .84s ease-in-out infinite}.no-gsap .agent[data-state="working"] .work-dots i{animation:potato-dot .68s ease-in-out infinite}.no-gsap .agent[data-state="working"] .work-dots i:nth-child(2){animation-delay:.1s}.no-gsap .agent[data-state="working"] .work-dots i:nth-child(3){animation-delay:.2s}.no-gsap .agent[data-state="calibrating"] .state-glyph{animation:potato-spin 2.4s linear infinite}.no-gsap .agent[data-state="calibrating"] .potato-body{animation:potato-pulse 1.5s ease-in-out infinite}.no-gsap .agent[data-state="error"] .potato-body{animation:potato-alert .8s ease-in-out infinite}.no-gsap .agent[data-state="offline"] .state-glyph{animation:potato-sleep 3s ease-in-out infinite}
    @media(prefers-reduced-motion:reduce){.no-gsap .agent *{animation:none!important}}
    @media(max-width:900px){.agent-row{grid-template-columns:1fr 1fr}}
    @media(max-width:700px){header{padding:0 18px}main{padding:34px 16px 54px}.launchers{grid-template-columns:1fr}.launcher{min-height:205px}.launcher h2{margin-top:28px}.tools-list{grid-template-columns:1fr}.tool{border-right:0;border-bottom:1px solid var(--line)}.tool:last-child{border-bottom:0}.agent-row{grid-template-columns:1fr}.heading time{display:none}}
  </style>
</head>
<body>
  <header><div class="mark">P</div><div class="brand">Potato 工作台</div><div class="gateway-state"><span class="dot"></span><span id="gatewayLabel">Gateway</span></div></header>
  <main>
    <div class="heading"><h1>总入口</h1><time id="clock"></time></div>
    <section class="launchers" aria-label="主要入口">
      <a class="launcher workflow" id="workflowLink" href="http://127.0.0.1:8787/workflows">
        <div class="topline"><div class="app-icon">WF</div><div class="arrow" aria-hidden="true">→</div></div>
        <h2>视频工作流</h2><div class="meta">Potato Hub · 8787</div>
        <div class="status-line" id="hubState">检查中</div>
      </a>
      <a class="launcher calibration" href="/calibrations">
        <div class="topline"><div class="app-icon">CA</div><div class="arrow" aria-hidden="true">→</div></div>
        <h2>Agent 校准</h2><div class="meta">Potato Gateway · 8765</div>
        <div class="status-line online">可用</div>
      </a>
    </section>
    <section class="tools"><div class="tools-head"><h2>工具</h2></div><div class="tools-list">
      <a class="tool" href="/docs"><div class="tool-icon">API</div><div><strong>接口文档</strong><span>Swagger UI</span></div><div class="go">→</div></a>
      <a class="tool" href="/potato-actions-v0.2.8.yaml"><div class="tool-icon">YML</div><div><strong>Actions Schema</strong><span>OpenAPI 3.1</span></div><div class="go">→</div></a>
      <a class="tool" id="hubHome" href="http://127.0.0.1:8787/"><div class="tool-icon">HUB</div><div><strong>Hub 消息台</strong><span>Session 与素材</span></div><div class="go">→</div></a>
    </div></section>
    <section id="agents" aria-labelledby="agentsTitle"><div class="agents-heading"><h2 id="agentsTitle">土豆状态</h2><span id="agentUpdated">正在连接</span></div><div class="agent-row" id="agentRow"><div class="agent-empty">正在读取四只土豆的状态…</div></div></section>
  </main>
  <script>
    const hubOrigin=`${location.protocol}//${location.hostname}:8787`;
    document.querySelector('#workflowLink').href=`${hubOrigin}/workflows`;
    document.querySelector('#hubHome').href=`${hubOrigin}/`;
    document.querySelector('#clock').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date());
    const token=()=>localStorage.getItem('potatoGatewayToken')||'';
    const agentRoles={researcher:'研究与素材',creator:'视频创作',critic:'质量审查',engineer:'开发与运维'};
    const agentIcons={researcher:'search',creator:'clapperboard',critic:'scan-eye',engineer:'wrench'};
    const stateLabels={idle:'空闲',working:'忙碌',calibrating:'校准中',error:'异常',offline:'离线',unknown:'未知'};
    if(window.gsap)document.documentElement.classList.remove('no-gsap');
    const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
    const mascotDetails={
      researcher:'<span class="scholar-cap"></span><span class="cap-tassel"></span><span class="glasses"><i class="glasses-bridge"></i></span><span class="bowtie"></span>',
      creator:'<span class="steam-puff one"></span><span class="steam-puff two"></span><span class="steam-puff three"></span><span class="clapper"></span><span class="play-dot"></span>',
      critic:'<span class="shreds"><i></i><i></i><i></i><i></i><i></i></span><span class="chili-mark"></span><span class="lime-slice"></span>',
      engineer:'<span class="circuit-antenna"></span><span class="digital-visor"></span><span class="code-badge">&lt;/&gt;</span><span class="pixel-tail"></span>'
    };
    let agentSignature='',agentMotion=null;
    function faceGlyph(state){if(state==='working')return '<span class="work-dots"><i></i><i></i><i></i></span>';if(state==='calibrating')return '◎';if(state==='error')return '!';if(state==='offline')return 'zZ';if(state==='unknown')return '?';return '♪'}
    function renderAgents(agents){const signature=JSON.stringify(agents.map(item=>[item.id,item.status,item.activity_state,item.activity_label]));if(signature===agentSignature)return;agentSignature=signature;document.querySelector('#agentRow').innerHTML=agents.map(item=>`<article class="agent" data-agent="${escapeHtml(item.id)}" data-state="${escapeHtml(item.activity_state)}" aria-label="${escapeHtml(item.display_name)}，${escapeHtml(stateLabels[item.activity_state]||item.activity_state)}，${escapeHtml(item.activity_label)}"><div class="potato-scene" aria-hidden="true"><div class="potato-body"><span class="eye left"></span><span class="eye right"></span><span class="cheek left"></span><span class="cheek right"></span><span class="mouth"></span>${mascotDetails[item.id]||''}</div><span class="state-glyph">${faceGlyph(item.activity_state)}</span></div><div class="agent-copy"><div class="agent-title"><i data-lucide="${agentIcons[item.id]||'circle'}" width="13"></i><b>${escapeHtml(item.display_name)}</b></div><span class="agent-role">${escapeHtml(agentRoles[item.id]||'')}</span><span class="agent-activity">${escapeHtml(item.activity_label)}</span><span class="agent-state">${escapeHtml(stateLabels[item.activity_state]||item.activity_state)}</span></div></article>`).join('');window.lucide?.createIcons();animateAgentStates()}
    function animateAgentStates(){agentMotion?.revert();if(!window.gsap)return;agentMotion=gsap.matchMedia();agentMotion.add('(prefers-reduced-motion: no-preference)',()=>{gsap.from('.agent',{y:7,autoAlpha:0,duration:.3,stagger:.04,ease:'power1.out'});gsap.utils.toArray('.agent[data-state="idle"] .potato-body').forEach(body=>{gsap.to(body,{scaleY:.97,scaleX:1.02,duration:1.8,repeat:-1,yoyo:true,ease:'sine.inOut'});gsap.to(body.querySelectorAll('.eye'),{scaleY:.08,duration:.1,repeat:-1,repeatDelay:2.8,yoyo:true,ease:'none'})});gsap.utils.toArray('.agent[data-state="working"] .potato-body').forEach(body=>gsap.to(body,{y:-3,rotation:2,duration:.42,repeat:-1,yoyo:true,ease:'power1.inOut'}));const animateIfPresent=(selector,vars)=>{const targets=gsap.utils.toArray(selector);if(targets.length)gsap.to(targets,vars)};animateIfPresent('.agent[data-state="working"] .work-dots i',{y:-3,duration:.34,repeat:-1,yoyo:true,stagger:.1,ease:'power1.inOut'});animateIfPresent('.agent[data-state="calibrating"] .state-glyph',{rotation:360,duration:2.4,repeat:-1,ease:'none'});animateIfPresent('.agent[data-state="calibrating"] .potato-body',{scale:1.035,duration:.75,repeat:-1,yoyo:true,ease:'sine.inOut'});animateIfPresent('.agent[data-state="error"] .potato-body',{rotation:3,duration:.16,repeat:3,yoyo:true,ease:'power1.inOut'});animateIfPresent('.agent[data-state="offline"] .state-glyph',{y:-4,autoAlpha:.42,duration:1.5,repeat:-1,yoyo:true,ease:'sine.inOut'})})}
    async function loadStatus(){
      if(!token()){document.querySelector('#hubState').textContent='打开工作流';document.querySelector('#agentRow').innerHTML='<div class="agent-empty">打开 Agent 校准并登录后，即可查看实时状态。</div>';document.querySelector('#agentUpdated').textContent='等待登录';return}
      try{
        const response=await fetch('/api/status',{headers:{Authorization:`Bearer ${token()}`}});
        if(!response.ok)throw new Error('status unavailable');
        const data=await response.json();
        const hub=document.querySelector('#hubState');
        hub.textContent=data.potato_hub.status==='online'?'在线':'暂不可用';
        hub.classList.remove('online','offline');hub.classList.add(data.potato_hub.status==='online'?'online':'offline');
        renderAgents(data.agents);
        document.querySelector('#agentUpdated').textContent=`${new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())} 更新`;
      }catch{document.querySelector('#hubState').textContent='打开工作流';document.querySelector('#agentUpdated').textContent='连接暂时中断'}
    }
    loadStatus();
    setInterval(loadStatus,8000);
    if(window.gsap&&!matchMedia('(prefers-reduced-motion: reduce)').matches){
      gsap.from('.launcher',{y:12,autoAlpha:0,duration:.38,stagger:.07,ease:'power1.out'});
      gsap.from('.tools',{y:8,autoAlpha:0,duration:.3,delay:.16,ease:'power1.out'});
    }
  </script>
</body></html>'''
